### ISSUE TITLE
[BUG] Panel crashes with “'NoneType' object is not subscriptable”

### ISSUE THREAD

**Issue by OlivierNicole** [nwg-piotr/nwg-panel#137]
Hi and thanks for all your work on nwg-shell.

**Describe the bug**
Sometimes the panel disappears. The entire terminal output is the following:
```
Dependencies check: {'light': True, 'brightnessctl': False, 'ddcutil': False, 'pamixer': True, 'pactl': True, 'playerctl': False, 'netifaces': True, 'btmgmt': True, 'wlr-randr': True, 'upower': True, 'swaync': False, 'python-requests': True}
Running on sway
Output: eDP-1, position: top, layer: bottom, width: 1920, height: 30

** (nwg-panel:1886896): WARNING **: 16:23:47.139: gtk-layer-shell v0.6.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
Traceback (most recent call last):
  File "/nix/store/vb7zp1cgfhmnirgwycj62pgg52spzqdl-nwg-panel-0.7.2/lib/python3.9/site-packages/nwg_panel/main.py", line 116, in check_tree
    item.refresh()
  File "/nix/store/vb7zp1cgfhmnirgwycj62pgg52spzqdl-nwg-panel-0.7.2/lib/python3.9/site-packages/nwg_panel/modules/sway_workspaces.py", line 106, in refresh
    ws_num, win_name, win_id, non_empty, win_layout = self.find_details()
  File "/nix/store/vb7zp1cgfhmnirgwycj62pgg52spzqdl-nwg-panel-0.7.2/lib/python3.9/site-packages/nwg_panel/modules/sway_workspaces.py", line 227, in find_details
    win_name = node.name[:self.settings["name-length"]]
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
Unfortunately I wasn't able to pin down what triggers this behavior yet.

**Expected behavior**
It shouldn't crash.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Linux distribution: NixOS 22.05
 - Sway version 1.7
 - Panel version 0.7.2

**Comment by nwg-piotr** [comment]
Try decreasing the window name length here:

![image](https://user-images.githubusercontent.com/20579136/183745003-3b3efce1-62a8-402b-b67f-8f42dbd4ba5a.png)

 I'll take a closer look at the issue as soon as I'm back from vacation (next week).

**Comment by nwg-piotr** [comment]
I had to fix blindly, but it should be ok now.

**Comment by OlivierNicole** [comment]
Thank you, it hasn't happened again so far.
