### ISSUE TITLE
[BUG] Installed requirements for different package and broke nwg

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-panel#138]
Stupid issue, but I recently installed the requirements for an old package on accident with pip and now nwg-panel wont start. I have tried rolling back to the old versions and did with what I could find through the respective requirements files, but it is still broken. At one point half was discolored and now it wont even start at all giving the error 

```
Dependencies check: {'light': True, 'brightnessctl': True, 'pamixer': True, 'pactl': True, 'playerctl': True, 'netifaces': True, 'btmgmt': True, 'wlr-randr': True, 'upower': True, 'swaync': True, 'python-requests': True}
Running on sway
Error loading json: Expecting ',' delimiter: line 275 column 28 (char 5933)
Traceback (most recent call last):
  File "/usr/bin/nwg-panel", line 33, in <module>
    sys.exit(load_entry_point('nwg-panel==0.7.1', 'gui_scripts', 'nwg-panel')())
  File "/usr/lib/python3.10/site-packages/nwg_panel/main.py", line 376, in main
    for panel in panels:
TypeError: 'NoneType' object is not iterable
```

I am not sure where to go from here, I have uninstalled nwg-panel from the repository and reinstalled and tried doing the same with the pip package to no avail. I would really like to be able to use this again please any assistance is very welcome. 

In the first place the problem was Mapping not being in collections so after making what I believed to be the correct changes I was able to get it to start but like I said it was discolored and not using my preset configs. I have tried investigating the json error it is bringing up but am unsure what file it is specifically. I checked my preset files and there should be no issue there.

Hope youre enjoying vacation!

**Comment by xi-pinmping** [comment]
Solution was as stupid as the problem, somehow I erased a single comma in the base config file and it was misreading it and making me believe pip had borked my installation. Fixed now
