### ISSUE TITLE
[BUG] Cannot use keepassxc trayicon

### ISSUE THREAD

**Issue by DVN196** [nwg-piotr/nwg-panel#158]
**Describe the bug**
When enabling `keepassxc`'s tray icon and `nwg-panel`'s tray. Keepassxc is frozen

**To Reproduce**
1. Enabling tray icon in keepassxc
2. Open nwg-panel

**Expected behavior**
Keepassxc should work normally

**Screenshots**
![2022-10-26-230236_screenshot](https://user-images.githubusercontent.com/23018009/198077167-ec9be53f-b00d-4c2b-ad82-c23261ec53c0.png)

**Desktop (please complete the following information):**
 - Archlinux
 - sway version 1.7
 - nwg-panel version 0.7.12

**Additional context**
Log:
```
Dependencies check: {'light': True, 'brightnessctl': False, 'ddcutil': False, 'pamixer': True, 'pactl': True, 'playerctl': True, 'netifaces': True, 'btmgmt': True, 'wlr-randr': False, 'upower': False, 'swaync': True, 'python-requests': True}
Running on sway
Panel 'top': output: HDMI-A-1, position: top, layer: bottom, width: 1920, height: 30
Panel 'bottom': output: HDMI-A-1, position: bottom, layer: bottom, width: 1920, height: 30

(nwg-panel:150250): Gtk-CRITICAL **: 22:58:20.436: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(nwg-panel:150250): Gtk-CRITICAL **: 22:58:20.436: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(nwg-panel:150250): Gtk-CRITICAL **: 22:58:20.436: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(nwg-panel:150250): Gtk-CRITICAL **: 22:58:20.436: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
```

**Comment by svenihoney** [comment]
* If I start keepassxc, it freezes and the nwg-panel freezes as well.
* If both applications are in frozen state, they can't even be stopped by CTRL-C
* If I stop keepassxc in this state by sending KILL signal (pkill -9 keepassxc), the nwg-panel bails out with the following exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dasbus/client/observer.py", line 88, in _name_appeared_callback
    callback(name_owner, *callback_args)
  File "/usr/lib/python3.10/site-packages/dasbus/client/observer.py", line 230, in _service_name_appeared_callback
    self._enable_service()
  File "/usr/lib/python3.10/site-packages/dasbus/client/observer.py", line 220, in _enable_service
    self._service_available.emit(self)
  File "/usr/lib/python3.10/site-packages/dasbus/signal.py", line 53, in emit
    callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/nwg_panel/modules/sni_system_tray/item.py", line 60, in item_available_handler
    self.item_proxy.PropertiesChanged.connect(
  File "/usr/lib/python3.10/site-packages/dasbus/client/proxy.py", line 161, in __getattr__
    member = self._get_member(self._get_interface(name), name)
  File "/usr/lib/python3.10/site-packages/dasbus/client/proxy.py", line 211, in _get_interface
    self._handler.specification.members
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 206, in specification
    self._specification = self._get_specification()
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 326, in _get_specification
    xml = self._call_method(
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 444, in _call_method
    return self._get_method_reply(
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
    return self._handle_method_error(error)
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
    raise exception from None
dasbus.error.DBusError: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 133, in _signal_callback
    callback(parameters, *callback_args)
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 359, in _signal_callback
    callback(*unwrap_variant(parameters))
  File "/usr/lib/python3.10/site-packages/dasbus/signal.py", line 53, in emit
    callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/nwg_panel/modules/sni_system_tray/host.py", line 94, in item_unregistered_handler
    tray.remove_item(item)
  File "/usr/lib/python3.10/site-packages/nwg_panel/modules/sni_system_tray/tray.py", line 197, in remove_item
    self.box.remove(self.items[full_service_name]["event_box"])
KeyError: ':1.1713/StatusNotifierItem'
```
* After stopping keepassxc the nwg-panel seems to continue just fine.

**Comment by nwg-piotr** [comment]
I don't think it's a panel bug. KeePassXC tray icon seems to be Wayland incompatible. See 
https://github.com/keepassxreboot/keepassxc/issues/6502 and more results for the "KeePassXC tray icon wayland" Google search.

**Comment by svenihoney** [comment]
Maybe there's a problem with Qt based applications not behaving correctly, but there is no reason that the panel completely hangs because of that IMHO.

BTW: Waybar works without problems.

**Comment by nwg-piotr** [comment]
Maybe it's possible to workaround in some way, but for now I have no idea. I'll get back to it when I have more time.

**Comment by varac** [comment]
I have the same problem for nextcloud-client. It freezes, as nwg-panel does immediatly. Not logs, but I can stop nextcloud-client using `<Ctrl+c>`. I wonder if I should create a new issue for this, because it seems to be a general issue with QT icons in nwg-panel ?

**Comment by varac** [comment]
This is really blocking, since I cannot use the nextcloud-desktop under nwg-shell. Anything I could do to help here ?

**Comment by varac** [comment]
@nwg-piotr I created #165 for the NC issue

**Comment by nwg-piotr** [comment]
Ok, but for now I have no idea where to start from.
