### ISSUE TITLE
[BUG] setuptools invalid version

### ISSUE THREAD

**Issue by Schievel1** [nwg-piotr/nwg-panel#281]
During packaging I get 
```
python3.11 -m gpep517 build-wheel --prefix=/usr --backend setuptools.build_meta:__legacy__ --output-fd 3 --wheel-dir /var/tmp/portage/gui-apps/nwg-panel-0.9.20/work/nwg-panel-0.9.20-python3_11/wheel
2024-01-10 12:25:23,743 gpep517 INFO Building wheel via backend setuptools.build_meta:__legacy__
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/setuptools/_normalization.py", line 64, in safe_version
    return str(packaging.version.Version(v))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.9.20.'
```

This is likely due to this space in the version string you introduced in this commit:https://github.com/nwg-piotr/nwg-panel/commit/dbf8dd7686517517322fedb2b31740acb5928151#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L11

is this for any particular reason?

**Comment by nwg-piotr** [comment]
No, just a typo, sorry. I didn't notice, as it builds on Arch. Will fix tonight.

**Comment by nwg-piotr** [comment]
64a0983

Can't release from the office, however. :/

**Comment by nwg-piotr** [comment]
https://github.com/nwg-piotr/nwg-panel/releases/tag/v0.9.21
