### ISSUE TITLE
[BUG] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by LudovicoPiero** [nwg-piotr/nwg-panel#300]
**Describe the bug**
Error on first time launch.

**To Reproduce**
1. Open `nwg-panel` on Hyprland.
2. Error.

**Expected behavior**
It will run without any error.

**Desktop (please complete the following information):**
 - Linux distribution `NixOS`
 - Hyprland version 
 ```console
Hyprland, built from branch  at commit 494b9415a1157279a1e1782ba635fc2ef6a18155  ().
Date: 2024-05-11
Tag: , commits: 

flags: (if any)
```
 - Panel version `nwg-panel version 0.9.31`

**Additional context**
Log
```console
❯ /nix/store/i5xhwjmp0g6p4idg7nsb1jqhjp97102p-nwg-panel-0.9.31/bin/nwg-panel                                                           
Creating '/home/airi/.config/nwg-panel'
Creating '/home/airi/.config/nwg-panel/icons_light'
Creating '/home/airi/.config/nwg-panel/icons_dark'
Creating '/home/airi/.config/nwg-panel/icons_color'
Creating '/home/airi/.config/nwg-panel/executors'
Common settings {'restart-on-display': True, 'restart-delay': 500, 'processes-backgroud-only': True, 'processes-own-only': True}
Dependencies check: {'light': False, 'brightnessctl': True, 'ddcutil': False, 'pamixer': True, 'pactl': True, 'playerctl': False, 'wlr-randr': True, 'hyprctl': True, 'upower': False, 'swaync': False, 'python-requests': True}
Copying '/home/airi/.config/nwg-panel/icons_light/user-available-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/gtk-close.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-low-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-full-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-low-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-03d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/umbrella.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/grid.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-09n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-empty-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/media-playback-start-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/media-skip-backward-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/mode.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-50d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/audio-volume-medium-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-11n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-13d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/display-brightness-high-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-01n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/pan-end-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-processes.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/display-brightness-medium-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/system-lock-screen.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/emblem-system-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-04n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/arch-notification.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/azote.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/system-shutdown-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-good-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/sunrise.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/edit-delete-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-look.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/arch-linux.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/go-down-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/measure.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-displays.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-shell-config.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-empty-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-clipman.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-02d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/wind.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/media-playback-pause-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/document-open-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/pressure.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/audio-volume-muted-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/cloud.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-10n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/view-refresh-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/github.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/display-brightness-low-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/audio-volume-low-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/view-dual-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-good-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-10d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/exclamation.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/gtk-apply.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-02n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-readme-browser.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/icon-theme.cache'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-04d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/music.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/media-skip-forward-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwgocc-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/humidity.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/pan-down-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-panel.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/eye.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/airplane-mode-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/edit-clear.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/audio-volume-high-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/sunset.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/view-paged-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/window-close-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-01d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/bell.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/blank.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-13n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/go-next-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/list-add-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/battery-full-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/icon-missing.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/window-pop-out-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-11d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-50n.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/nwg-shell.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-09d.svg'
Copying '/home/airi/.config/nwg-panel/icons_light/ow-03n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-10n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-02d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/music.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/arch-notification.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-good-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/humidity.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-panel.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-full-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/pan-end-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/user-available-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/airplane-mode-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-04n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/edit-delete-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/gtk-apply.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/exclamation.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/window-close-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/audio-volume-high-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-shell-config.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/bell.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-01n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-13d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/go-down-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-readme-browser.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/edit-clear.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-full-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-shell.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/display-brightness-high-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-50d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-11n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-low-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/view-dual-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-03d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/display-brightness-low-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-09n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/blank.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/icon-theme.cache'
Copying '/home/airi/.config/nwg-panel/icons_dark/view-refresh-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/audio-volume-muted-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/view-paged-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-good-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-empty-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-09d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/grid.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/measure.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-03n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/audio-volume-low-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-11d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-50n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/mode.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwgocc-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/gtk-close.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-13n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/list-add-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-01d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/arch-linux.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/system-lock-screen.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/umbrella.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/media-playback-pause-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-displays.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/sunset.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-empty-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/sunrise.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/system-shutdown-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/media-skip-forward-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/display-brightness-medium-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/battery-low-charging-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/eye.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-clipman.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/cloud.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/document-open-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/pressure.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-04d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/media-playback-start-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/wind.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-02n.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/azote.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/ow-10d.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/emblem-system-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/window-pop-out-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/pan-down-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/media-skip-backward-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/go-next-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/audio-volume-medium-symbolic.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-processes.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/nwg-look.svg'
Copying '/home/airi/.config/nwg-panel/icons_dark/github.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-01n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-13d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-11n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-50d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-09n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-03d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-10n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-02d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-04n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-04d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-02n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-10d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-03n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-09d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-50n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-11d.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-13n.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/exclamation.svg'
Copying '/home/airi/.config/nwg-panel/icons_color/ow-01d.svg'
Copying '/home/airi/.config/nwg-panel/executors/airplane_mode.py', marking executable
Copying '/home/airi/.config/nwg-panel/executors/github.sh', marking executable
Copying '/home/airi/.config/nwg-panel/executors/check-notifications', marking executable
Copying '/home/airi/.config/nwg-panel/executors/arch_updates.py', marking executable
Copying '/home/airi/.config/nwg-panel/executors/au.sh', marking executable
Copying '/home/airi/.config/nwg-panel/config'
Copying '/home/airi/.config/nwg-panel/style.css'
Running on Hyprland
Traceback (most recent call last):
  File "/nix/store/i5xhwjmp0g6p4idg7nsb1jqhjp97102p-nwg-panel-0.9.31/bin/.nwg-panel-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/i5xhwjmp0g6p4idg7nsb1jqhjp97102p-nwg-panel-0.9.31/lib/python3.11/site-packages/nwg_panel/main.py", line 575, in main
    common.outputs = list_outputs(sway=sway, tree=tree)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/i5xhwjmp0g6p4idg7nsb1jqhjp97102p-nwg-panel-0.9.31/lib/python3.11/site-packages/nwg_panel/tools.py", line 304, in list_outputs
    monitors = json.loads(output)
               ^^^^^^^^^^^^^^^^^^
  File "/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by LudovicoPiero** [comment]
Fixed on version `0.9.32`
