### ISSUE TITLE
[BUG] nwg-panel crashes when trying to put hyprland-workspaces before hyprland-taskbar in module list

### ISSUE THREAD

**Issue by 31JSON** [nwg-piotr/nwg-panel#315]
**Describe the bug**
When configuring the panel, I wanted to put `hyprland-workspaces` module before `hyprland-taskbar` on the left hand side of the panel. Doing so causes a crash in `nwg-panel`. The reverse order works fine, but is not my desired order.

**To Reproduce**
1. Open nwg-panel config.
2. Add `hyprland-workspaces` followed by `hyprland-taskbar` to the list of modules.
3. Relaunch

**Expected behavior**
The modules show in the correct order and `nwg-panel` doesn't crash.

**Desktop (please complete the following information):**
 - Arch Linux
 - Hyprland v. 0.41.2
 - Panel version 0.4.9

**Additional context**
```
Running instance found, PID 208513, sending SIGINT
Running instance found, PID 210161, sending SIGINT
PID 208513 still alive, sending SIGKILL
PID 210161 still alive, sending SIGKILL
Common settings {'restart-on-display': True, 'restart-delay': 500, 'processes-background-only': False, 'processes-own-only': True, 'processes-interval-ms': 2000}
Dependencies check: {'light': False, 'brightnessctl': True, 'ddcutil': True, 'pamixer': False, 'pactl': True, 'playerctl': True, 'wlr-randr': False, 'hyprctl': True, 'upower': True, 'swaync': True, 'python-requests': True}
Running on Hyprland
Traceback (most recent call last):
  File "/usr/bin/nwg-panel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 763, in main
    instantiate_content(panel, left_box, panel["modules-left"], icons_path=icons_path)
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 338, in instantiate_content
    taskbar = HyprlandTaskbar(panel["hyprland-taskbar"], panel["position"], monitors, workspaces,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/hyprland_taskbar.py", line 44, in __init__
    self.refresh(monitors, workspaces, clients, activewindow)
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/hyprland_taskbar.py", line 70, in refresh
    self.parse_workspaces(workspaces)
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/hyprland_taskbar.py", line 57, in parse_workspaces
    self.ws_nums.append(item["id"])
                        ~~~~^^^^^^
TypeError: 'Box' object is not subscriptable
```

**Comment by nwg-piotr** [comment]
There's a GUI for panel configuration. If you prefer editing json files manually, your typos are your problem.

**Comment by 31JSON** [comment]
If you read my bug report, you will see that I used the GUI.

**Comment by nwg-piotr** [comment]
Sorry, I should have read more carefully. Will take a look at this.

**Comment by nwg-piotr** [comment]
This should fix the issue. Thanks for reporting and sorry once again for closing at first.
