### ISSUE TITLE
[BUG] per-app volume sliders crash on virtual sinks

### ISSUE THREAD

**Issue by baitmooth** [nwg-piotr/nwg-panel#327]
**Describe the bug**
I'd love to use the 'per app volume', but the slider never appears (traceback below)

**To Reproduce**

1. check `per-app volume`
2. start one or more audio streams
3. open menu

**Expected behavior**
see the individual streams

**Additional context and screenshots**
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 585, in on_window_show
    self.create_per_app_sliders()
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 595, in create_per_app_sliders
    props = sink_inputs[inp]["Properties"]
            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'Properties'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 159, in update_brightness
    self.popup_window.refresh()
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 684, in refresh
    props = sink_inputs[inp]["Properties"]
            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'Properties'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 684, in refresh
    props = sink_inputs[inp]["Properties"]
            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'Properties'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 159, in update_brightness
    self.popup_window.refresh()
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 684, in refresh
    props = sink_inputs[inp]["Properties"]
            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'Properties'
```
![swappy-20241011_150311](https://github.com/user-attachments/assets/db8f010b-fce8-4687-a294-dd5025dd9310)
![sway_screenshot](https://github.com/user-attachments/assets/08579fad-bfd7-4522-86f2-cfabd74c9b27)

Since i guess that this works for others, what are the dependencies for this?

**Comment by nwg-piotr** [comment]
Do you have pactl installed?

**Comment by baitmooth** [comment]
`pactl list sink-inputs`
```Ziel-Eingabe #14
	Treiber: module-combine-sink.c
	Besitzer-Modul: 14
	Client: k. A.
	Ziel: 0
	Abtastwert-Angabe: s16le 2ch 44100Hz
	Kanalzuordnung: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Unterbrochen: nein
	Stumm: nein
	Lautstärke: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        Verteilung 0,00
	Pufferlatenz: 181 usec
	Ziel-Latenz: 199117 usec
	Resample-Methode: speex-float-1
	Eigenschaften:
		media.name = "Simultaneous output on Internes Audio Analog Stereo"
		media.role = "filter"
		module-stream-restore.id = "sink-input-by-media-role:filter"

Ziel-Eingabe #15
	Treiber: protocol-native.c
	Besitzer-Modul: 12
	Client: 18793
	Ziel: 1
	Abtastwert-Angabe: s16le 2ch 44100Hz
	Kanalzuordnung: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Unterbrochen: nein
	Stumm: nein
	Lautstärke: front-left: 65133 /  99% / -0,16 dB,   front-right: 65133 /  99% / -0,16 dB
	        Verteilung 0,00
	Pufferlatenz: 139206 usec
	Ziel-Latenz: 199276 usec
	Resample-Methode: k. A.
	Eigenschaften:
		media.name = "Pulse Audio Output"
		application.name = "Music Player Daemon"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		media.role = "music"
		application.icon_name = "mpd"
		application.process.id = "201484"
		application.process.user = "pan"
		application.process.host = "oxylos"
		application.process.binary = "mpd"
		application.language = "C"
		window.x11.display = ":0"
		application.process.machine_id = "23442cfc25cc46a9bf46d48d165c486d"
		module-stream-restore.id = "sink-input-by-media-role:music"```

**Comment by nwg-piotr** [comment]
LOL, I had no idea that `pactl` gave localized output. Surely my parser makes no use of German values. I'll add `LC_ALL=C`, but won't release another version tonight, in order not to infuriate packagers. Possibly adding `alias pactl=LC_ALL=C pactl` to your ~/.bashrc could help, but I have no way to check it, as pactl has no Polish localization.

**Comment by baitmooth** [comment]
This happens now in terminal
```
KeyError: 'application.name'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 159, in update_brightness
    self.popup_window.refresh()
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/controls.py", line 694, in refresh
    scale = PerAppSlider(inp, vol, icon_name, props["application.name"], props["media.name"])
```
Still no per-app volume :(

**Comment by nwg-piotr** [comment]
May I see the output of `LC_ALL=C pactl list sink-inputs`?

**Comment by nwg-piotr** [comment]
I just set up a testing environment in German, on my old laptop. Hoped to nail the bug here, but everything works as expected, especially per-app sliders. Also, the pactl output is in English. 

![grafik](https://github.com/user-attachments/assets/c03288c7-8022-4843-a11a-84277e689686)

**Comment by baitmooth** [comment]
Hej. You are right it is working
![working](https://github.com/user-attachments/assets/33d04153-2f12-4263-9391-faf6083dad50)
…**unless** i activate pulseaudios virtual sink for simultanious output.

**Comment by nwg-piotr** [comment]
Well, I don't know what your pactl output looks like in English, and also I know nothing about virtual sinks. That means I have no fix for your issue.

**Comment by baitmooth** [comment]
> Well, I don't know what your pactl output looks like in English

Totally forgot that.

without simultaneous output
```
LC_ALL=C pactl list sink-inputs
Sink Input #3
	Driver: protocol-native.c
	Owner Module: 12
	Client: 589
	Sink: 0
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Corked: no
	Mute: no
	Volume: front-left: 63569 /  97% / -0.79 dB,   front-right: 63569 /  97% / -0.79 dB
	        balance 0.00
	Buffer Latency: 16326 usec
	Sink Latency: 4575 usec
	Resample method: n/a
	Properties:
		media.name = "Audio Stream"
		application.name = "python3.12"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "3325"
		application.process.user = "pan"
		application.process.host = "oxylos"
		application.process.binary = "python3.12"
		application.language = "de_DE.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "23442cfc25cc46a9bf46d48d165c486d"
		application.process.session_id = "3"
		module-stream-restore.id = "sink-input-by-application-name:python3.12"

Sink Input #17
	Driver: protocol-native.c
	Owner Module: 12
	Client: 352
	Sink: 0
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Corked: no
	Mute: no
	Volume: front-left: 100270 / 153% / 11.08 dB,   front-right: 100270 / 153% / 11.08 dB
	        balance 0.00
	Buffer Latency: 244444 usec
	Sink Latency: 4541 usec
	Resample method: n/a
	Properties:
		media.name = "Pulse Audio Output"
		application.name = "Music Player Daemon"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		media.role = "music"
		application.icon_name = "mpd"
		application.process.id = "1495"
		application.process.user = "pan"
		application.process.host = "oxylos"
		application.process.binary = "mpd"
		application.language = "C"
		application.process.machine_id = "23442cfc25cc46a9bf46d48d165c486d"
		module-stream-restore.id = "sink-input-by-media-role:music"
```
with simultaneous output
```
LC_ALL=C pactl list sink-inputs
Sink Input #17
	Driver: protocol-native.c
	Owner Module: 12
	Client: 352
	Sink: 7
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Corked: no
	Mute: no
	Volume: front-left: 100270 / 153% / 11.08 dB,   front-right: 100270 / 153% / 11.08 dB
	        balance 0.00
	Buffer Latency: 238798 usec
	Sink Latency: 12643 usec
	Resample method: n/a
	Properties:
		media.name = "Pulse Audio Output"
		application.name = "Music Player Daemon"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		media.role = "music"
		application.icon_name = "mpd"
		application.process.id = "1495"
		application.process.user = "pan"
		application.process.host = "oxylos"
		application.process.binary = "mpd"
		application.language = "C"
		application.process.machine_id = "23442cfc25cc46a9bf46d48d165c486d"
		module-stream-restore.id = "sink-input-by-media-role:music"

Sink Input #18
	Driver: module-combine-sink.c
	Owner Module: 29
	Client: n/a
	Sink: 0
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Corked: no
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Buffer Latency: 181 usec
	Sink Latency: 199723 usec
	Resample method: speex-float-1
	Properties:
		media.name = "Simultaneous output on Internes Audio Analog Stereo"
		media.role = "filter"
		module-stream-restore.id = "sink-input-by-media-role:filter"
```

At this point I would say let's change the title of the bug first. Since it is related to the virtual sink. 

To me it looks like You check application name per sink. And virtual one does not have one. I guess if there would be a check for either `Driver: module-combine-sink.c` (which should be same on all systems), or `media.role = "filter"` (which might differ)?

**Comment by baitmooth** [comment]
Skipping this would be okay, since I can control it with the other output selection slider.

**Comment by nwg-piotr** [comment]
OK, I'll do so. This is the simplest solution.
