### ISSUE TITLE
[BUG] crash on launch (Scratchpad module?)

### ISSUE THREAD

**Issue by japhir** [nwg-piotr/nwg-panel#367]
**Describe the bug**
The panel does not lauch. If I launch from command line, I get an error message (see below).

**To Reproduce**
1. launch nwg-panel without options from command line
2. See error

**Expected behavior**
Launch the panel on multiple monitors.

**Screenshots**

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - Sway version `sway -v`: 1.10
 - Panel version `nwg-panel -v`: 0.9.55

**Additional context**
Maybe it's because I use the Scratchpad module and something changed there?
I've disabled it and it still doesn't run (see end).

Does this rely on wine somehow?

```
$ nwg-panel
Common settings {'restart-on-display': True, 'restart-delay': 500}
Dependencies check: {'light': True, 'brightnessctl': True, 'ddcutil': True, 'pamixer': True, 'pactl': True, 'playerctl': True, 'wlr-randr': True, 'hyprctl': False, 'upower': True, 'swaync': True, 'python-requests': True}
Running on sway
Outputs: {'eDP-1': {'x': 3840, 'y': 520, 'width': 1920, 'height': 1080, 'description': 'LG Display 0x0521 Unknown', 'monitor': <__gi__.GdkWaylandMonitor object at 0x7443147f7400 (GdkWaylandMonitor at 0x5c2ede3c4b10)>}, 'DP-1': {'x': 0, 'y': 0, 'width': 3840, 'height': 1600, 'description': 'LG Electronics LG HDR WQHD+ 209NTTQGN817', 'monitor': <__gi__.GdkWaylandMonitor object at 0x7443147f7440 (GdkWaylandMonitor at 0x5c2ede3c4d30)>}}
Descriptions: {'LG Display 0x0521 Unknown': 'eDP-1', 'LG Electronics LG HDR WQHD+ 209NTTQGN817': 'DP-1'}
left box created
center box created
/home/japhir/.cache/nwg-dwl-data data file not found
Traceback (most recent call last):
  File "/usr/bin/nwg-panel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 773, in main
    instantiate_content(panel, right_box, panel["modules-right"], icons_path=icons_path)
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 282, in instantiate_content
    scratchpad = Scratchpad(common.i3, common.i3.get_tree(), panel[item], panel["output"],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/scratchpad.py", line 35, in __init__
    self.check_scratchpad(i3.get_tree())
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/scratchpad.py", line 52, in check_scratchpad
    icon = get_icon_name(node.app_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/icons.py", line 85, in get_icon_name
    __populate_caches()
  File "/usr/lib/python3.12/site-packages/nwg_panel/icons.py", line 77, in __populate_caches
    __process_desktop_file(file_path)
  File "/usr/lib/python3.12/site-packages/nwg_panel/icons.py", line 35, in __process_desktop_file
    with open(file_path, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/japhir/.local/share/applications/wine'
```

I have temporarily disabled the Scratchpad module and then it still does not run

<details> <summary> here's the output for that </summary>
```
nwg-panel -c preset-1 -s preset-1.css

Running instance found, PID 263201, sending SIGINT
PID 263201 still alive, sending SIGKILL
Common settings {'restart-on-display': True, 'restart-delay': 500}
Dependencies check: {'light': True, 'brightnessctl': True, 'ddcutil': True, 'pamixer': True, 'pactl': True, 'playerctl': True, 'wlr-randr': True, 'hyprctl': False, 'upower': True, 'swaync': True, 'python-requests': True}
Running on sway
Outputs: {'eDP-1': {'x': 3840, 'y': 520, 'width': 1920, 'height': 1080, 'description': 'LG Display 0x0521 Unknown', 'monitor': <__gi__.GdkWaylandMonitor object at 0x77d8820b32c0 (GdkWaylandMonitor at 0x60e3b59b8cb0)>}, 'DP-1': {'x': 0, 'y': 0, 'width': 3840, 'height': 1600, 'description': 'LG Electronics LG HDR WQHD+ 209NTTQGN817', 'monitor': <__gi__.GdkWaylandMonitor object at 0x77d8820b3300 (GdkWaylandMonitor at 0x60e3b59d3820)>}}
Descriptions: {'LG Display 0x0521 Unknown': 'eDP-1', 'LG Electronics LG HDR WQHD+ 209NTTQGN817': 'DP-1'}
gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /home/japhir/.config/nwg-panel/preset1.css: No such file or directory (2)
left box created
center box created
right box created
Panel 'bottom-inbox': output: eDP-1, monitor: , position: bottom, layer: bottom, width: 1920, height: 4
left box created
center box created
right box created
Panel 'top': output: eDP-1, monitor: , position: top, layer: bottom, width: 1920, height: 24
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 668, in create_pixbuf
    raise ValueError("icons_path not supplied.")
ValueError: icons_path not supplied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 671, in create_pixbuf
    pixbuf = icon_theme.load_icon(icon_name, icon_size, Gtk.IconLookupFlags.FORCE_SIZE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'nwg-panel-config' not present in theme Yaru-dark (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 630, in update_image_fallback_desktop
    update_image(image, icon_name, icon_size, fallback=False)
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 622, in update_image
    pixbuf = create_pixbuf(icon_name, icon_size, icons_path, fallback)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 679, in create_pixbuf
    raise e
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 673, in create_pixbuf
    pixbuf = icon_theme.load_icon(icon_name.lower(), icon_size, Gtk.IconLookupFlags.FORCE_SIZE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'nwg-panel-config' not present in theme Yaru-dark (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nwg-panel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 751, in main
    instantiate_content(panel, left_box, panel["modules-left"], icons_path=icons_path)
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 258, in instantiate_content
    taskbar = SwayTaskbar(panel["sway-taskbar"], common.i3, panel["position"],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/sway_taskbar.py", line 39, in __init__
    self.build_box()
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/sway_taskbar.py", line 84, in build_box
    win_box = WindowBox(self.tree, con, self.settings, self.position, self.icons_path,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/sway_taskbar.py", line 160, in __init__
    update_image_fallback_desktop(image, name, settings["image-size"], icons_path)
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 633, in update_image_fallback_desktop
    icon_from_desktop = get_icon_name(icon_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/icons.py", line 85, in get_icon_name
    __populate_caches()
  File "/usr/lib/python3.12/site-packages/nwg_panel/icons.py", line 77, in __populate_caches
    __process_desktop_file(file_path)
  File "/usr/lib/python3.12/site-packages/nwg_panel/icons.py", line 35, in __process_desktop_file
    with open(file_path, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/japhir/.local/share/applications/wine'
```
</details>

**Comment by japhir** [comment]
Oh maybe there's something wrong with the AUR package?

```
❯ paru nwg-panel
2 aur/nwg-panel-git r1041.ef79fb8-1 [+1 ~0.18]
    GTK3-based panel for sway Wayland compositor
1 extra/nwg-panel 0.9.55-1 [366.58 KiB 3.32 MiB] [Installed]
    GTK3-based panel for sway and Hyprland Wayland compositors
:: Packages to install (eg: 1 2 3, 1-3):
:: 1
warning: nwg-panel-0.9.55-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) nwg-panel-0.9.55-1

Total Download Size:   0.36 MiB
Total Installed Size:  3.32 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 nwg-panel-0.9.55-1-any                                                                 366.6 KiB   509 KiB/s 00:01 [#####################################################################] 100%
error: failed retrieving file 'nwg-panel-0.9.55-1-any.pkg.tar.zst' from mirror.netcologne.de : The requested URL returned error: 404
error: failed retrieving file 'nwg-panel-0.9.55-1-any.pkg.tar.zst.sig' from mirror.osbeck.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
```

**Comment by yawor** [comment]
There's definitely a bug in the processing of desktop files. In the `nwg_panel.icons` module, the `__populate_caches()` method iterates over a list of directories with desktop files and then lists each directory's entries and calls `__process_desktop_file()` method on that entry, which in turn calls `open()` on it. The problem is that these directories can not only contain desktop files, but also subdirectories. And when `__process_desktop_file()` is called on a subdirectory instead of a desktop file, then the `IsADirectoryError` exception is raised and it's not being caught.

A proper implementation should check if the entry is a directory and insert it back into the list, so the subdirectory is then also iterated over. I'd also take into consideration whether to handle symlinks or just ignore them. If symlinks where to be handled, then a cautions need to be taken not to enter an infinite loop if there's a symlink back to one of the parent directories, which would create a loop. Maybe there should be a set of already processed directories which would then be checked if the directory has already been seen.

**Comment by nwg-piotr** [comment]
@pol-rivero

**Comment by pol-rivero** [comment]
Oh, I hadn't considered that :(
I was going to bed now, tomorrow morning I will submit a hotfix.

Do those subdirectories contain .desktop files that should be scanned for icons? This way I know if they should be recursively scanned or just ignored.

**Comment by nwg-piotr** [comment]
According to [this issue](https://github.com/nwg-piotr/nwg-drawer/issues/142), recursive search may be necessary in some cases. Personally I've never had such a need.

**Comment by yawor** [comment]
Yes, they can contain desktop files. For example wine creates its own subdirectory for desktop files to programs installed in wine, etc.

**Comment by pol-rivero** [comment]
Understood, the new method will also scan subdirectories. If it's easy to implement, I will also follow symlinks with some depth limit.

**Comment by nwg-piotr** [comment]
@pol-rivero  I wouldn't care about symlinks, but the solution is up to you.

**Comment by pol-rivero** [comment]
Yes, it's probably unnecessary. However the depth limit will be trivial to implement so we might as well support symlinks to avoid confusion.

**Comment by nwg-piotr** [comment]
I absolutely trust your judgment.

**Comment by yawor** [comment]
I've created a PR with a fix. I've used a set() for already seen directories instead of max depth like @pol-rivero mentioned. It also uses `os.path.realpath` to resolve a real path if there's a symlink anywhere. Using max-depth could be a little tricky, as I didn't want to use recursion to traverse the directory tree and instead I use a list as a stack of dirs.

**Comment by nwg-piotr** [comment]
Let's leave it until the morning. The PR fixes @pol-rivero 's job, so I'd like him to express an opinion.

**Comment by pol-rivero** [comment]
LGTM
Your proper DFS is better than the quick fix I would have done. I added one small nitpick as a comment to your PR, in case you want to add it before it gets merged.
