### ISSUE TITLE
[BUG] some nwg-panel configs crash on start with "icons_path not supplied."

### ISSUE THREAD

**Issue by nergdron** [nwg-piotr/nwg-panel#373]
**Describe the bug**
Sometime over the holidays, I've ran into a weird error where multiple nwg-panel configs fail to load, including my current customized config that's been working for months. There seems to have been some change with icon theme handling perhaps, because the primary error causing the crash is "icons_path not supplied." in `File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 668, in create_pixbuf`.

This occurs with my customized panel config, but also with the config `hyprland-2`, which I haven't touched since installing. the `hyprland-1` and `hyprland-3` presets work fine, so it's unclear to me what's going on.

**To Reproduce**
1. Switch nwg-panel config to `hyprland-2` preset config.
2. hit apply.
3. see panel vaporize because it doesn't load properly.
4. See error maybe. might be because these presets were generated by a much older version of nwg-shell/panel.

**Expected behavior**
panel loads properly

**Screenshots**

**Desktop (please complete the following information):**
 - arch
```
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


flags set:
debug
```
 - Panel version `nwg-panel -v`
```
nwg-panel version 0.9.58
```

**Additional context**
I suspect there's something that's changed or been fixed in more recent releases that my older configs haven't changed. I'd love to figure out what has changed and just correct it, so I can keep using my custom panel config, but the error doesn't give me much to go on. Here's the full errors from the cli when running manually:

```
nwg-panel -c hyprland-1                                                                                                                                 ✔   4s  󰊭 sudo  21:09:02 
Common settings {'restart-on-display': True, 'restart-delay': 500, 'processes-background-only': False, 'processes-own-only': True, 'processes-interval-ms': 2000}
Dependencies check: {'light': False, 'brightnessctl': True, 'ddcutil': False, 'pamixer': False, 'pactl': True, 'playerctl': True, 'wlr-randr': True, 'hyprctl': True, 'upower': True, 'swaync': True, 'python-requests': True}
Running on Hyprland
Outputs: {'DP-2': {'x': 0, 'y': 0, 'width': 3072, 'height': 1728, 'description': 'Dell Inc. AW3225QF 97H0YZ3', 'monitor': <__gi__.GdkWaylandMonitor object at 0x71240d56d100 (GdkWaylandMonitor at 0x5856eec84700)>}}
Descriptions: {'Dell Inc. AW3225QF 97H0YZ3': 'DP-2'}
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 668, in create_pixbuf
    raise ValueError("icons_path not supplied.")
ValueError: icons_path not supplied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 671, in create_pixbuf
    pixbuf = icon_theme.load_icon(icon_name, icon_size, Gtk.IconLookupFlags.FORCE_SIZE)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'focus-windows' not present in theme Yaru-magenta-dark (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 630, in update_image_fallback_desktop
    update_image(image, icon_name, icon_size, fallback=False)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 622, in update_image
    pixbuf = create_pixbuf(icon_name, icon_size, icons_path, fallback)
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 679, in create_pixbuf
    raise e
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 673, in create_pixbuf
    pixbuf = icon_theme.load_icon(icon_name.lower(), icon_size, Gtk.IconLookupFlags.FORCE_SIZE)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'focus-windows' not present in theme Yaru-magenta-dark (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nwg-panel", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/main.py", line 767, in main
    instantiate_content(panel, left_box, panel["modules-left"], icons_path=icons_path)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/main.py", line 327, in instantiate_content
    workspaces = HyprlandWorkspaces(panel["hyprland-workspaces"], monitors, workspaces, clients,
                                    activewindow, activeworkspace, icons_path=icons_path)
  File "/usr/lib/python3.13/site-packages/nwg_panel/modules/hyprland_workspaces.py", line 25, in __init__
    self.refresh(monitors, workspaces, clients, activewindow, activeworkspace)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/modules/hyprland_workspaces.py", line 154, in refresh
    update_image_fallback_desktop(self.floating_icon, "focus-windows", self.settings["image-size"],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                  self.icons_path)
                                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/tools.py", line 633, in update_image_fallback_desktop
    icon_from_desktop = get_icon_name(icon_name)
  File "/usr/lib/python3.13/site-packages/nwg_panel/icons.py", line 85, in get_icon_name
    __populate_caches()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/icons.py", line 77, in __populate_caches
    __process_desktop_file(file_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/nwg_panel/icons.py", line 35, in __process_desktop_file
    with open(file_path, "r", encoding="utf-8") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/tessa/.local/share/applications/wine'
```

I've tried switching my icon theme to a bunch of different ones, since all the complaints are about icons, but it hasn't made any difference. would love some guidance about what's going wrong here and how to fix it. :sweat_smile:

**Comment by nwg-piotr** [comment]
This is most probably related to what #370 fixes. I'll release latest changes soon. Check if the issue still exist and let me know, please.

**Comment by nergdron** [comment]
@nwg-piotr oh yeah, updated to the latest `nwg-panel` and switched back to my old config, and it seems good. thanks so much!
