### ISSUE TITLE
SwayTaskbar crashes when opening LibreOffice

### ISSUE THREAD

**Issue by CIAvash** [nwg-piotr/nwg-panel#58]
Or more specifically I think the LibreOffice splash/loading screen crashes the taskbar.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nwg_panel/main.py", line 80, in check_tree
    item.refresh(tree)
  File "/usr/lib/python3.9/site-packages/nwg_panel/modules/sway_taskbar.py", line 77, in refresh
    self.build_box()
  File "/usr/lib/python3.9/site-packages/nwg_panel/modules/sway_taskbar.py", line 68, in build_box
    win_box = WindowBox(con, self.settings, self.position, self.icons_path, floating=con in desc.floating_nodes)
  File "/usr/lib/python3.9/site-packages/nwg_panel/modules/sway_taskbar.py", line 127, in __init__
    icon_from_desktop = get_icon(name)
  File "/usr/lib/python3.9/site-packages/nwg_panel/tools.py", line 80, in get_icon
    if "GIMP" in app_name.upper():
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by nwg-piotr** [comment]
Yes, it crashes on undefined name. Thank you for reporting, I'll fix it.
