### ISSUE TITLE
Trying to get running on sway / EndeavourOS

### ISSUE THREAD

**Issue by xircon** [nwg-piotr/nwg-panel#99]
```
 killl waybar && nwg-panel&
[1] 613262
2022-03-22 20:13 ➜ .config/sway/config.d ✦ ➜ Couldn't load system tray, is 'python-dbus' installed?
Traceback (most recent call last):
  File "/usr/bin/nwg-panel", line 33, in <module>
    sys.exit(load_entry_point('nwg-panel==0.6.2', 'gui_scripts', 'nwg-panel')())
  File "/usr/bin/nwg-panel", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nwg_panel/main.py", line 72, in <module>
    common.i3 = Connection()
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 74, in __init__
    self._cmd_socket.connect(self._socket_path)
FileNotFoundError: [Errno 2] No such file or directory
```
python-dbus is installed (or dbus-python is! :smile: Any ideas?

**Comment by xircon** [comment]
It's python-dasbus !!

**Comment by nwg-piotr** [comment]
Actually that's what the module is called. I'll have to fix this message, thanks.
